name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write
  pull-requests: write
  packages: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        
      - name: Lint
        run: biome ci --no-errors-on-unmatched .

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup and Install
        id: install
        uses: ./.github/actions/setup-and-install
        with:
          node-version: 20

      # - name: Start LocalStack
      #   uses: LocalStack/setup-localstack@v0.2.2
      #   with:
      #     image-tag: 'latest'
      #     install-awslocal: 'true'

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:ci

      - name: Coverage
        if: ${{ steps.install.conclusion == 'success' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          vite-config-path: vitest.root.ts