name: Test

on:
  workflow_call:

jobs:
  test:
    name: Unit
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup and Install
        id: install
        uses: ./.github/actions/setup-and-install
        with:
          node-version: 20

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: 'latest'
          install-awslocal: 'true'

      - name: Test
        run: pnpm test

      - name: Coverage
        if: ${{ steps.install.conclusion == 'success' }}
        uses: davelosert/vitest-coverage-report-action@v2